version: '3.9'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    depends_on:
      - frontend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules   # Prevent overwriting node_modules inside the container
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
